"""Generating Ollama Modelfiles for the models a project is configured to use.

Ollama has three places a context window can be set, and they do not agree:

    PARAMETER num_ctx        in a Modelfile   — per model, wins
    OLLAMA_CONTEXT_LENGTH    in the server env — one number for every model
    the desktop app's own settings database    — overrides neither reliably

A project that pins per model in a Modelfile gets one answer per model and
nothing global can quietly undercut it. Getting there by hand is where the
mistakes live: one real setup carried `num_ctx 32768` in three Modelfiles for
weeks, which silently capped models trained for eight times that, and the only
symptom was a budget the loop could not explain.

Two sampling knobs belong here rather than in `config.json`, and this is not a
preference. Measured against Ollama 0.32: `top_p 0.01` collapses six samples to
one, and `top_k 1` leaves all six distinct. The OpenAI-compatible endpoint
accepts `top_k` and `min_p` and applies neither, so the Modelfile is the only
place they take effect. `temperature` and `top_p` do reach the model per
request and stay in config, where they can differ per role.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

MODELS_DIR = "models"

# Sampling defaults when the base model ships none of its own. `top_k 20` is
# the value every current open-weights recipe converges on; `min_p 0` disables
# a filter that interacts badly with the low temperatures a pipeline wants.
_FALLBACK_TOP_K = 20
_FALLBACK_MIN_P = 0


def _shipped(parameters: str) -> dict[str, str]:
    """The base model's own `PARAMETER` lines, as `/api/show` reports them."""
    found: dict[str, str] = {}
    for line in (parameters or "").splitlines():
        parts = line.split(None, 1)
        if len(parts) == 2:
            found.setdefault(parts[0].strip(), parts[1].strip().strip('"'))
    return found


def render(
    model: str,
    *,
    num_ctx: int,
    shipped: dict[str, str] | None = None,
    trained: int | None = None,
) -> str:
    """One Modelfile, pinning the window and the knobs config cannot reach."""
    shipped = shipped or {}
    top_k = shipped.get("top_k", str(_FALLBACK_TOP_K))
    min_p = shipped.get("min_p", str(_FALLBACK_MIN_P))

    note = ""
    if trained and trained > num_ctx:
        note = (
            f"# This model was trained for {trained:,}. The smaller window below is\n"
            f"# what the project asked for — a larger KV cache has to fit in VRAM\n"
            f"# alongside the weights, and `forge doctor` reports when it does not.\n"
        )

    return (
        f"FROM {model}\n"
        f"#\n"
        f"# Generated by `forge models`. Rebuild after editing:\n"
        f"#     ollama create <name> -f <this file>\n"
        f"#\n"
        f"# num_ctx is pinned per model rather than through OLLAMA_CONTEXT_LENGTH,\n"
        f"# which is one number for every model and silently overrides this file.\n"
        f"{note}"
        f"PARAMETER num_ctx {num_ctx}\n"
        f"#\n"
        f"# Ollama's OpenAI-compatible endpoint accepts top_k and min_p and applies\n"
        f"# neither, so they only take effect here. temperature and top_p do reach\n"
        f"# the model per request and belong in config.json, where they can differ\n"
        f"# from role to role.\n"
        f"PARAMETER top_k {top_k}\n"
        f"PARAMETER min_p {min_p}\n"
    )


class Entry:
    """One model's generated Modelfile, and what to do with it."""

    def __init__(self, alias: str, base: str, create_as: str, text: str, rename: bool):
        self.alias = alias
        # What the Modelfile is `FROM` — the real weights, never a tuned alias
        # of them.
        self.base = base
        # What `ollama create` should be told to build.
        self.create_as = create_as
        self.text = text
        # True when `create_as` is a new name config does not use yet, so
        # applying this also means editing config. False when config already
        # names a tuned alias and rebuilding it is safe.
        self.rename = rename

    @property
    def command(self) -> str:
        return f"ollama create {self.create_as} -f"


def plan(config: Any) -> list[Entry]:
    """A Modelfile for every Ollama-backed model in the config.

    Non-Ollama endpoints are skipped rather than guessed at: a Modelfile means
    nothing to vLLM or OpenRouter, and writing one would imply otherwise.

    The name to build under is the careful part. When config already points at
    a tuned alias, `/api/show` reports its `parent_model` and rebuilding that
    same alias is safe. When config points straight at a base model there is
    no parent, and building under that name would *overwrite the weights the
    Modelfile is FROM* — so a new name is proposed instead, and applying it
    means editing config too.
    """
    from .providers import build_provider

    out: list[Entry] = []
    for alias in sorted(config.models):
        block = config.model_block(alias)
        if block.get("kind") != "openai":
            continue
        try:
            provider = build_provider(alias, block)
        except Exception:  # noqa: BLE001 - a broken block is doctor's to report
            continue
        if getattr(provider, "_native_url", lambda: None)() is None:
            continue

        found: dict[str, int] = {}
        shipped: dict[str, str] = {}
        parent = ""
        try:
            found = provider._ollama_context()
            info = provider._ollama_show()
            shipped = _shipped(info.get("parameters", ""))
            parent = (info.get("details") or {}).get("parent_model") or ""
        except Exception:  # noqa: BLE001 - offline still produces a usable file
            pass
        if not found and not block.get("contextWindow"):
            continue

        trained = found.get("trained")
        num_ctx = int(block.get("contextWindow") or found.get("served") or trained or 0)
        if num_ctx <= 0:
            continue

        configured = block["model"]
        base = parent or configured
        create_as = configured if parent else f"forge-{alias}"
        out.append(Entry(
            alias, base, create_as,
            render(base, num_ctx=num_ctx, shipped=shipped, trained=trained),
            rename=not parent,
        ))
    return out


def write(config: Any) -> list[tuple[Entry, Path]]:
    """Write a Modelfile per Ollama-backed model. Returns what was written."""
    directory = config.config_dir / MODELS_DIR
    written: list[tuple[Entry, Path]] = []
    entries = plan(config)
    if entries:
        directory.mkdir(parents=True, exist_ok=True)
    for entry in entries:
        path = directory / f"Modelfile.{entry.alias}"
        path.write_text(entry.text, encoding="utf-8")
        written.append((entry, path))
    return written
