"""Generating the llama.cpp preset a project's models are served from.

`llama-server --models-preset <file>` reads an INI where each section is a model
id and each key is a server flag without its leading dashes. The router spawns
one child server per section, on an ephemeral port, and proxies by that id. So
the preset *is* the deployment: what gets loaded, with what context window,
with which sampler and reasoning settings.

That makes it the one place a run's local models are actually configured, and
the one place a mistake is invisible. Two are worth naming, because both were
paid for on real runs:

**The context window is the preset's, not the model's.** A checkpoint trained
for 262,144 serves whatever `--ctx-size` its child was spawned with. Forge reads
that argv back rather than the GGUF metadata, so `contextWindow` in config and
`ctx-size` here have to agree — and when they do not, the budget gate plans
against a window the server will truncate from the front, dropping the system
prompt and the spec.

**A thinking model with no reasoning budget spends the whole output budget
thinking.** Measured: a 30B A3B MoE burned all 32,768 of its output tokens on
hidden reasoning and never began its answer, on every call, until
`reasoning-budget` was set. `forge doctor` reports a preset with no budget on a
model whose replies come back empty, but the fix belongs here.

Written rather than hand-maintained for the same reason Modelfiles were, back
when Ollama was a backend: the numbers have to agree with `config.json`, and
keeping two files in step by hand is where the silent failures live.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

MODELS_DIR = "models"
PRESET_NAME = "llamacpp.ini"

# Config key -> preset flag, for the settings that belong to the *server* rather
# than to a request. Sampling that varies per role stays in config.json and is
# sent on each call; these cannot be, because they decide how the child server
# is spawned.
_SERVER_KEYS: tuple[tuple[str, str], ...] = (
    ("contextWindow", "ctx-size"),
    ("reasoningBudget", "reasoning-budget"),
    ("reasoningEffort", "reasoning-effort"),
    ("gpuLayers", "n-gpu-layers"),
    ("flashAttention", "flash-attn"),
    ("cacheTypeK", "cache-type-k"),
    ("cacheTypeV", "cache-type-v"),
    ("parallel", "parallel"),
    ("mainGpu", "main-gpu"),
    ("splitMode", "split-mode"),
)


def _ini_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


class Entry:
    """One model's section of the preset."""

    def __init__(self, alias: str, model_id: str, path: str, settings: dict[str, Any]):
        # The config key this came from, for error messages a person recognises.
        self.alias = alias
        # The router's id for it, which is what `model` in config must name.
        self.model_id = model_id
        # The .gguf on disk.
        self.path = path
        self.settings = settings

    def render(self) -> str:
        lines = [f"[{self.model_id}]", f"model = {self.path}"]
        for key, value in self.settings.items():
            lines.append(f"{key} = {_ini_value(value)}")
        return "\n".join(lines) + "\n"


def render(entries: list[Entry]) -> str:
    """The whole preset file, header and all."""
    header = (
        "; Generated by `forge models`. Serve it with:\n"
        ";\n"
        f";     llama-server --models-preset {PRESET_NAME} --models-max 1\n"
        ";\n"
        "; Each section name is the id the router answers to, and is what\n"
        "; `model` in .hybridforge/config.json must name. `ctx-size` here and\n"
        "; `contextWindow` there have to agree: forge plans a prompt against\n"
        "; config and the server truncates against this, and what a too-large\n"
        "; window loses is the front of the prompt — the system message and\n"
        "; the spec.\n"
    )
    if not entries:
        return header
    return header + "\n" + "\n".join(entry.render() for entry in entries)


def plan(config: Any) -> list[Entry]:
    """A preset section for every llama.cpp-backed model in the config.

    Cloud models are skipped: a preset means nothing to an endpoint forge does
    not start. A local model with no `modelPath` is skipped too rather than
    guessed at — the .gguf it should serve is not derivable from an id, and a
    section pointing at the wrong file fails at load with a message about the
    file rather than about the config that named it.

    Models sharing a router id collapse into one section, because they are one
    child server. Two roles pointing at the same checkpoint is the ordinary
    case, not a mistake.
    """
    from .providers import LlamaCppProvider

    out: list[Entry] = []
    seen: dict[str, Entry] = {}
    for alias in sorted(config.models):
        block = config.model_block(alias)
        kind = str(block.get("kind", LlamaCppProvider.kind)).lower()
        if kind not in ("llamacpp", "llama.cpp", "llama-cpp", "llama-server", "llama", "local"):
            continue
        path = str(block.get("modelPath") or "").strip()
        if not path:
            continue
        model_id = str(block.get("model") or alias)

        settings: dict[str, Any] = {"jinja": True}
        for key, flag in _SERVER_KEYS:
            value = block.get(key)
            if value is not None and value != "":
                settings[flag] = value
        # The multimodal projector is loaded automatically beside a .gguf that
        # has one, and costs VRAM no text-only role will use.
        if block.get("multimodal") is not True:
            settings["mmproj-auto"] = False
        settings.update(block.get("presetFlags") or {})

        if model_id in seen:
            # Same child server, so one set of spawn flags for both roles. A
            # later role may add a flag the first did not; where both set the
            # same one, last-wins would make the file depend on the order of
            # keys in `config.json`.
            #
            # `ctx-size` takes the largest asked for, and the direction is the
            # whole point. Each role plans against its own `contextWindow`, and
            # a server serving *more* than a role planned for is harmless —
            # serving less is the failure that truncates a prompt from the
            # front and takes the system message and the spec with it.
            merged = seen[model_id].settings
            for flag, value in settings.items():
                if flag == "ctx-size" and flag in merged:
                    merged[flag] = max(int(merged[flag]), int(value))
                else:
                    merged[flag] = value
            continue
        entry = Entry(alias, model_id, path, settings)
        seen[model_id] = entry
        out.append(entry)
    return out


def write(config: Any) -> Path | None:
    """Write the preset. Returns where it went, or None when there is nothing local."""
    entries = plan(config)
    if not entries:
        return None
    directory = config.config_dir / MODELS_DIR
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / PRESET_NAME
    path.write_text(render(entries), encoding="utf-8")
    return path
